services:
  - type: web
    name: flask-react-app
    env: python
    buildCommand: |
      pip install pipenv
      pipenv install --deploy --ignore-pipfile
      cd client && npm install && npm run build && cd ..
    startCommand: pipenv run gunicorn server.app:app
    envVars:
      - key: FLASK_ENV
        value: production
